version: '3'

services:
  stablediffusion:
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    build: ./docker/stablediffusion
    ipc: host
    # volumes:
    #     - ./docker/stablediffusion/src:/usr/src/app
    labels:
      - "traefik.http.routers.sd-secure.rule=Host(`127.0.0.1`) || Host(`sd.traefik.me`)"
      - "traefik.http.routers.sd-secure.tls=true"
      - "traefik.http.routers.sd.rule=Host(`127.0.0.1`) || Host(`sd.traefik.me`)"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
    command: ./webui.sh --listen
    ports:
      - "7860:7860"
  
  flowise:
    build: ./docker/flowise
    restart: unless-stopped
    environment:
      - PORT=8282
      - CORS_ORIGINS=${CORS_ORIGINS}
      - IFRAME_ORIGINS=${IFRAME_ORIGINS}
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
      - FLOWISE_FILE_SIZE_LIMIT=${FLOWISE_FILE_SIZE_LIMIT}
      - DEBUG=true
      - DATABASE_PATH=/root/.flowise
      - DATABASE_TYPE=mysql
      - DATABASE_PORT=3306
      - DATABASE_HOST=database
      - DATABASE_NAME=aisuite
      - DATABASE_USER=aisuite
      - DATABASE_PASSWORD=xxaisuitexx
      - DATABASE_SSL=false
      - OVERRIDE_DATABASE=true
      - DATABASE_SSL_KEY_BASE64=${DATABASE_SSL_KEY_BASE64}
      - APIKEY_PATH=/root/.flowise
      - SECRETKEY_PATH=/root/.flowise
      - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=/root/.flowise/logs
      - BLOB_STORAGE_PATH=/root/.flowise/storage
      - DISABLE_FLOWISE_TELEMETRY=${DISABLE_FLOWISE_TELEMETRY}
    labels:
      - "traefik.http.routers.flowise-secure.rule=Host(`127.0.0.1`) || Host(`flowise.traefik.me`)"
      - "traefik.http.routers.flowise-secure.tls=true"
      - "traefik.http.routers.flowise.rule=Host(`127.0.0.1`) || Host(`flowise.traefik.me`)"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
    ports:
      - '8282:8282'
    volumes:
      - ./docker/flowise/.flowise:/root/.flowise
    command: /bin/sh -c "sleep 3; flowise start"

  database:
    ipc: host
    image: mysql:8.0.32
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: aisuite
      MYSQL_USER: aisuite
      MYSQL_PASSWORD: xxaisuitexx
      MYSQL_DATABASE: aisuite
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./docker/redis:/data

  chromadb:
    ipc: host
    image: chromadb/chroma:latest
    volumes:
      - ./docker/chromadb:/chroma/chroma
    ports:
      - 8000:8000
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/chroma/chroma}
      - CHROMA_HOST_ADDR=chromadb
      - CHROMA_HOST_PORT=8000

  localai:
    tty: true
    stdin_open: true
    ipc: host
    ports:
        - 8081:8080
    deploy:
        resources:
            reservations:
                devices:
                    - driver: nvidia
                      count: all
                      capabilities:
                          - gpu
    image: localai/localai:v2.9.0-cublas-cuda12-core
    command: mixtral-instruct mistral-openorca bert-cpp all-minilm-l6-v2
    volumes:
      - ./docker/localai:/build/models
    labels:
      - "traefik.http.routers.localai-secure.rule=Host(`127.0.0.1`) || Host(`localai.traefik.me`)"
      - "traefik.http.routers.localai-secure.tls=true"
      - "traefik.http.routers.localai.rule=Host(`127.0.0.1`) || Host(`localai.traefik.me`)"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"

  traefik:
    restart: unless-stopped
    image: traefik:2.10
    ports:
      - "80:80"
      - "443:443"
      - "8180:8180"
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8180"
    volumes:
      - ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./docker/traefik/tls.yml:/etc/traefik/tls.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/cert:/etc/ssl/traefik
# chromadb
    # environment:
      # - CHROMA_API_IMPL="chromadb.api.fastapi.FastAPI"
      # - CHROMA_SERVER_HTTP_PORT=8484
      # - CHROMA_DB_IMPL=clickhouse
      # - CLICKHOUSE_HOST=clickhouse
      # - CLICKHOUSE_PORT=8123
      # - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["http://localhost:8585"]
#   command: "--workers 1 --host 0.0.0.0 --port 8484 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"

  # vllm:
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities:
  #               - gpu
  #   labels:
  #     - "traefik.http.routers.vllm-secure.rule=Host(`127.0.0.1`) || Host(`vllm.traefik.me`)"
  #     - "traefik.http.routers.vllm-secure.tls=true"
  #     - "traefik.http.routers.vllm.rule=Host(`127.0.0.1`) || Host(`vllm.traefik.me`)"
  #     - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
  #   ports:
  #     - 7474:7474
  #   volumes:
  #     - ~/.cache/huggingface:/root/.cache/huggingface
  #   ipc: host
  #   image: vllm/vllm-openai:latest 
  #   command: --model mistralai/Mistral-7B-Instruct-v0.2 --max-model-len 15400 --port 7474
