#!/bin/bash
if [ "$1" == "start" ];
then
docker compose -p aisuite --profile default up -d
fi

if [ "$1" == "stop" ];
then
docker compose -p aisuite stop
fi

if [ "$1" == "flowise" ];
then
docker compose -p aisuite exec --user=root flowise sh
fi

if [ "$1" == "chromadb" ];
then
docker compose -p aisuite exec --user=root chromadb sh
fi

if [ "$1" == "qdrant" ];
then
docker compose -p aisuite exec --user=root qdrant sh
fi

if [ "$1" == "stablediffusion" ];
then
docker compose -p aisuite exec --user=root stablediffusion sh
fi

if [ "$1" == "redis" ];
then
docker compose -p aisuite exec --user=root redis redis-cli
fi

if [ "$1" == "langflow" ];
then
docker compose -p aisuite exec --user=root langflow sh
fi

if [ "$1" == "n8n" ];
then
docker compose -p aisuite exec --user=root n8n sh
fi

if [ "$1" == "import-n8n-workflows" ]; then
  docker compose -p aisuite exec n8n n8n import:credentials --separate --input=/home/node/templates/credentials/
  docker compose -p aisuite exec n8n n8n import:workflow --separate --input=/home/node/templates/workflow/
fi

if [ "$1" == "flushcache" ];
then
docker compose -p aisuite exec --user=root redis redis-cli flushall
fi

if [ "$1" == "mkcert" ];
then
sudo apt update && sudo apt install libnss3-tools
curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"	
chmod +x mkcert-v*-linux-amd64
sudo mv mkcert-v*-linux-amd64 /usr/local/bin/mkcert
mkcert -install
mkcert "*.traefik.me"
mv _wildcard.traefik.me.pem ./docker/traefik/cert/cert.pem
mv _wildcard.traefik.me-key.pem ./docker/traefik/cert/privkey.pem
fi

