logLevel: INFO

accessLog:
    filePath: "traefik.log"
    
api:
    insecure: true
    dashboard: true

entryPoints:
    http:
        address: ":80"
    https:
        address: ":443"

providers:
    file:
        filename: /etc/traefik/tls.yml
    docker:
        endpoint: unix:///var/run/docker.sock
        watch: true
        exposedByDefault: true
        defaultRule: "HostRegexp(`localai.traefik.me`,`{{ index .Labels \"com.docker.compose.service\"}}-{dashed-ip:.*}.traefik.me`)"

